# Generated by Django 5.2.9 on 2026-01-07 06:10

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_role', models.CharField(choices=[('Admin', 'Quản trị viên'), ('Patient', 'Bệnh nhân'), ('Employee', 'Nhân viên')], max_length=20)),
                ('employee_role', models.CharField(blank=True, choices=[('Doctor', 'Bác sĩ'), ('Nurse', 'Y tá'), ('Pharmacist', 'Dược sĩ')], max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Nam'), ('Female', 'Nữ'), ('Other', 'Khác')], max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('address', models.TextField(blank=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nurse_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nurse_license', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_diseases', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('registered_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistProfile',
            fields=[
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pharmacist_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pharmacist_license', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('salary', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('doctor_license', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('total_patients', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='clinic.specialty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
