# Generated by Django 5.2.9 on 2026-01-07 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_record', serialize=False, to='clinic.appointment')),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Đã chỉ định'), ('PROCESSING', 'Đang thực hiện'), ('COMPLETED', 'Đã có kết quả'), ('CANCELLED', 'Đã hủy')], default='REQUESTED', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('confirmed_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
