# Generated by Django 5.2.9 on 2026-01-03 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0002_initial'),
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testorder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testorder',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='medical.medicalrecord'),
        ),
        migrations.AddField(
            model_name='testorder',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testorder',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_orders', to='clinic.service'),
        ),
    ]
