# Generated by Django 5.2.9 on 2026-01-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importreceipt',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
