# Generated by Django 5.2.9 on 2026-01-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_importreceipt_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importreceipt',
            name='code',
        ),
    ]
