# Generated by Django 5.2.9 on 2026-01-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_remove_importreceipt_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importdetail',
            old_name='price',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='dispenselog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='importreceipt',
            name='date',
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
