# Generated by Django 5.2.9 on 2025-12-28 06:16

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('type', models.CharField(blank=True, choices=[('ONLINE', 'Tư vấn trực tuyến'), ('OFFLINE', 'Khám tại phòng khám')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('IN_PROCESS', 'Đang khám'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('patient_note', models.TextField(blank=True)),
                ('employee_note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('duration', models.IntegerField(default=30)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('date', models.DateField()),
                ('day_of_week', models.IntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6'), (5, 'Thứ 7'), (6, 'Chủ nhật')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift', models.CharField(blank=True, choices=[('MORNING', 'Sáng (6:00 - 12:00)'), ('AFTERNOON', 'Chiều (12:00 - 18:00)'), ('EVENING', 'Tối (18:00 - 23:00)'), ('NIGHT', 'Khuya (0:00 - 6:00)'), ('OTHER', 'Khác')], max_length=20)),
                ('is_appointable', models.BooleanField(default=True)),
            ],
        ),
    ]
