# Generated by Django 5.2.9 on 2026-01-07 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('method', models.CharField(blank=True, choices=[('CASH', 'Tiền mặt'), ('BANKING', 'Chuyển khoản')], max_length=20, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.appointment')),
            ],
        ),
    ]
