# Generated by Django 5.2.9 on 2026-01-03 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PAID', 'Đã thanh toán'), ('REFUNDED', 'Đã hoàn tiền')], default='UNPAID', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Tiền mặt'), ('BANKING', 'Chuyển khoản')], max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='clinic.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
