# Generated by Django 5.2.9 on 2026-01-07 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('APPOINTMENT_CREATED', 'Lịch hẹn mới được tạo'), ('APPOINTMENT_CONFIRMED', 'Lịch hẹn được xác nhận'), ('APPOINTMENT_CANCELLED', 'Lịch hẹn bị hủy'), ('APPOINTMENT_REMINDER', 'Nhắc nhở lịch hẹn'), ('APPOINTMENT_STARTED', 'Lịch hẹn đã bắt đầu'), ('APPOINTMENT_COMPLETED', 'Lịch hẹn hoàn thành'), ('TEST_ORDER_CREATED', 'Xét nghiệm được chỉ định'), ('TEST_ORDER_CONFIRMED', 'Xét nghiệm được xác nhận'), ('TEST_ORDER_COMPLETED', 'Kết quả xét nghiệm đã có'), ('TEST_ORDER_CANCELLED', 'Xét nghiệm bị hủy'), ('PRESCRIPTION_CREATED', 'Đơn thuốc đã được kê'), ('PRESCRIPTION_UPDATED', 'Đơn thuốc đã được cập nhật'), ('SCHEDULE_APPROVED', 'Lịch làm việc được duyệt'), ('SYSTEM_ANNOUNCEMENT', 'Thông báo hệ thống'), ('PAYMENT_SUCCESS', 'Thanh toán thành công'), ('PAYMENT_FAILED', 'Thanh toán thất bại')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
