# Generated by Django 5.2.9 on 2026-01-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('APPOINTMENT_CREATED', 'Lịch hẹn mới được tạo'), ('APPOINTMENT_CONFIRMED', 'Lịch hẹn được xác nhận'), ('APPOINTMENT_CANCELLED', 'Lịch hẹn bị hủy'), ('APPOINTMENT_REMINDER', 'Nhắc nhở lịch hẹn'), ('APPOINTMENT_STARTED', 'Lịch hẹn đã bắt đầu'), ('APPOINTMENT_COMPLETED', 'Lịch hẹn hoàn thành'), ('TEST_ORDER_REQUESTED', 'Xét nghiệm đã được chỉ định'), ('TEST_ORDER_PROCESSING', 'Xét nghiệm đang được xử lý'), ('TEST_ORDER_COMPLETED', 'Kết quả xét nghiệm đã có'), ('TEST_ORDER_CANCELLED', 'Xét nghiệm bị hủy'), ('PRESCRIPTION_CREATED', 'Đơn thuốc đã được bác sĩ kê'), ('PRESCRIPTION_COMPLETED', 'Đơn thuốc đã hoàn tất'), ('PAYMENT_CREATED', 'Thanh toán mới được tạo'), ('PAYMENT_SUCCESS', 'Thanh toán thành công'), ('PAYMENT_FAILED', 'Thanh toán thất bại'), ('SCHEDULE_CONFIRMED', 'Lịch làm việc đã được xác nhận'), ('SYSTEM_ANNOUNCEMENT', 'Thông báo hệ thống')], max_length=50),
        ),
    ]
